apiVersion: apps/v1
kind: Deployment
metadata:
  name: cus-app
  labels:
    app: cus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cus-app
  template:
    metadata:
      labels:
        app: cus-app
    spec:
      containers:
      - name: cus-app
        image: nikiarya/cusmanagement:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8045


---
apiVersion: v1
kind: Service
metadata:
  name: cus-server
spec:
  type: NodePort
  selector:
    app: cus-app
  ports:
    - protocol: TCP
      port: 8045
      targetPort: 8045