apiVersion: apps/v1
kind: Deployment
metadata:
  name: cus-app
  labels:
    app: cus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cus-app
  template:
    metadata:
      labels:
        app: cus-app
    spec:
      containers:
      - name: cus-app
        image: nikiarya/cusmanagement:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: cus-server
spec:
  type: LoadBalancer
  selector:
    app: cus-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80